#include "fastfall/engine/input/Input_Def.hpp"

/*

const std::map<sf::Keyboard::Key, std::string> Input::keyToString = {
    {sf::Keyboard::Key::Unknown,   "Unknown"}, //!< Unhandled key
    {sf::Keyboard::Key::A,         "A"},
    {sf::Keyboard::Key::B,         "B"},
    {sf::Keyboard::Key::C,         "C"},
    {sf::Keyboard::Key::D,         "D"},
    {sf::Keyboard::Key::E,         "E"},
    {sf::Keyboard::Key::F,         "F"},
    {sf::Keyboard::Key::G,         "G"},
    {sf::Keyboard::Key::H,         "H"},
    {sf::Keyboard::Key::I,         "I"},
    {sf::Keyboard::Key::J,         "J"},
    {sf::Keyboard::Key::K,         "K"},
    {sf::Keyboard::Key::L,         "L"},
    {sf::Keyboard::Key::M,         "M"},
    {sf::Keyboard::Key::N,         "N"},
    {sf::Keyboard::Key::O,         "O"},
    {sf::Keyboard::Key::P,         "P"},
    {sf::Keyboard::Key::Q,         "Q"},
    {sf::Keyboard::Key::R,         "R"},
    {sf::Keyboard::Key::S,         "S"},
    {sf::Keyboard::Key::T,         "T"},
    {sf::Keyboard::Key::U,         "U"},
    {sf::Keyboard::Key::V,         "V"},
    {sf::Keyboard::Key::W,         "W"},
    {sf::Keyboard::Key::X,         "X"},
    {sf::Keyboard::Key::Y,         "Y"},
    {sf::Keyboard::Key::Z,         "Z"},
    {sf::Keyboard::Key::Num0,      "0"},
    {sf::Keyboard::Key::Num1,      "1"},
    {sf::Keyboard::Key::Num2,      "2"},
    {sf::Keyboard::Key::Num3,      "3"},
    {sf::Keyboard::Key::Num4,      "4"},
    {sf::Keyboard::Key::Num5,      "5"},
    {sf::Keyboard::Key::Num6,      "6"},
    {sf::Keyboard::Key::Num7,      "7"},
    {sf::Keyboard::Key::Num8,      "8"},
    {sf::Keyboard::Key::Num9,      "9"},
    {sf::Keyboard::Key::Escape,    "Escape"},
    {sf::Keyboard::Key::LControl,  "Left Control"},
    {sf::Keyboard::Key::LShift,    "Left Shift"},
    {sf::Keyboard::Key::LAlt,      "Left Alt"},
    {sf::Keyboard::Key::LSystem,   "Left System"},
    {sf::Keyboard::Key::RControl,  "Right Control"},
    {sf::Keyboard::Key::RShift,    "Right Shift"},
    {sf::Keyboard::Key::RAlt,      "Right Alt"},
    {sf::Keyboard::Key::RSystem,   "Right System"},
    {sf::Keyboard::Key::Menu,      "Menu"},
    {sf::Keyboard::Key::LBracket,  "["},
    {sf::Keyboard::Key::RBracket,  "]"},
    {sf::Keyboard::Key::Semicolon, ";"},
    {sf::Keyboard::Key::Comma,     ","},
    {sf::Keyboard::Key::Period,    "."},
    {sf::Keyboard::Key::Quote,     "'"},
    {sf::Keyboard::Key::Slash,     "/"},
    {sf::Keyboard::Key::Backslash, "\\"},
    {sf::Keyboard::Key::Tilde,     "~"},
    {sf::Keyboard::Key::Equal,     "="},
    {sf::Keyboard::Key::Hyphen,    "-"},
    {sf::Keyboard::Key::Space,     "Space"},
    {sf::Keyboard::Key::Enter,     "Enter"},
    {sf::Keyboard::Key::Backspace, "Backspace"},
    {sf::Keyboard::Key::Tab,       "Tab"},
    {sf::Keyboard::Key::PageUp,    "Page up"},
    {sf::Keyboard::Key::PageDown,  "Page down"},
    {sf::Keyboard::Key::End,       "End"},
    {sf::Keyboard::Key::Home,      "Home"},
    {sf::Keyboard::Key::Insert,    "Insert"},
    {sf::Keyboard::Key::Delete,    "Delete"},
    {sf::Keyboard::Key::Add,       "Num+"},
    {sf::Keyboard::Key::Subtract,  "Num-"},
    {sf::Keyboard::Key::Multiply,  "Num*"},
    {sf::Keyboard::Key::Divide,    "Num/"},
    {sf::Keyboard::Key::Left,      "Left"},
    {sf::Keyboard::Key::Right,     "Right"},
    {sf::Keyboard::Key::Up,        "Up"},
    {sf::Keyboard::Key::Down,      "Down"},
    {sf::Keyboard::Key::Numpad0,   "Num0"},
    {sf::Keyboard::Key::Numpad1,   "Num1"},
    {sf::Keyboard::Key::Numpad2,   "Num2"},
    {sf::Keyboard::Key::Numpad3,   "Num3"},
    {sf::Keyboard::Key::Numpad4,   "Num4"},
    {sf::Keyboard::Key::Numpad5,   "Num5"},
    {sf::Keyboard::Key::Numpad6,   "Num6"},
    {sf::Keyboard::Key::Numpad7,   "Num7"},
    {sf::Keyboard::Key::Numpad8,   "Num8"},
    {sf::Keyboard::Key::Numpad9,   "Num9"},
    {sf::Keyboard::Key::F1,        "F1"},
    {sf::Keyboard::Key::F2,        "F2"},
    {sf::Keyboard::Key::F3,        "F3"},
    {sf::Keyboard::Key::F4,        "F4"},
    {sf::Keyboard::Key::F5,        "F5"},
    {sf::Keyboard::Key::F6,        "F6"},
    {sf::Keyboard::Key::F7,        "F7"},
    {sf::Keyboard::Key::F8,        "F8"},
    {sf::Keyboard::Key::F9,        "F9"},
    {sf::Keyboard::Key::F10,       "F10"},
    {sf::Keyboard::Key::F11,       "F11"},
    {sf::Keyboard::Key::F12,       "F12"},
    {sf::Keyboard::Key::F13,       "F13"},
    {sf::Keyboard::Key::F14,       "F14"},
    {sf::Keyboard::Key::F15,       "F15"},
    {sf::Keyboard::Key::Pause,     "Pause"},
};

*/